#!/bin/bash 
jupyter trust "Asia/Asia logical structure.ipynb"
jupyter trust "Asia/Asia run model.ipynb"
jupyter trust "Asia/Carbon tax experiments.ipynb"
jupyter trust "Asia/Impact of global carbon tax rates, with revenue channelled back into the economy.ipynb"
jupyter trust "Asia/Overview.ipynb"
jupyter trust "Asia/Set carbon emission targets.ipynb"
jupyter trust "Asia/Set relative carbon emission targets .ipynb"
jupyter trust "Asia/test Asia new widget.ipynb"
jupyter trust "Asia/test Asia updatetab.ipynb"
jupyter trust "Asia/test output widgets .ipynb"
jupyter nbextension enable hide_input_all/main
jupyter nbextension enable splitcell/splitcell
exec "$@"